[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[theme]
primaryColor = "#2ecc71"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
